spring:
  application:
    name: FunSiesSpr

  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: strongpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

